-- Sample Campus Events for Cairo locations
-- Date range: August 27, 2025 to April 1, 2026

INSERT INTO events (title, description, category, location, event_date, event_time, organizer) VALUES
('Welcome Week Orientation', 'Introduction to campus life and academic programs for new students', 'Academic', 'Cairo University Main Campus, Giza', '2025-08-27', '09:00', 'Student Affairs Office'),
('Tech Innovation Summit', 'Latest trends in technology and innovation showcase', 'Technology', 'American University in Cairo, New Cairo', '2025-09-05', '10:00', 'Computer Science Department'),
('Cultural Heritage Festival', 'Celebrating Egyptian culture and traditions', 'Cultural', 'Al-Azhar Park, Islamic Cairo', '2025-09-12', '16:00', 'Cultural Committee'),
('Career Fair 2025', 'Meet top employers and explore career opportunities', 'Career', 'Cairo International Convention Center, Nasr City', '2025-09-18', '09:00', 'Career Services'),
('Sports Day Championship', 'Inter-university sports competition', 'Sports', 'Cairo Stadium, Heliopolis', '2025-09-25', '08:00', 'Sports Club'),
('Art Exhibition Opening', 'Contemporary Egyptian art showcase', 'Cultural', 'Opera House, Zamalek', '2025-10-02', '18:00', 'Fine Arts Department'),
('Entrepreneurship Workshop', 'Building your startup from idea to execution', 'Workshop', 'Tahrir Lounge, Downtown Cairo', '2025-10-10', '14:00', 'Business School'),
('Science Fair', 'Student research presentations and experiments', 'Academic', 'Egyptian Museum, Tahrir Square', '2025-10-17', '10:00', 'Science Faculty'),
('Music Concert: Cairo Beats', 'Local and international music performances', 'Entertainment', 'Cairo Opera House, Zamalek', '2025-10-24', '20:00', 'Music Society'),
('Halloween Party', 'Costume party with games and prizes', 'Social', 'Maadi Community Center, Maadi', '2025-10-31', '19:00', 'Student Union'),
('Photography Workshop', 'Learn professional photography techniques', 'Workshop', 'Khan El Khalili, Old Cairo', '2025-11-07', '09:00', 'Photography Club'),
('Book Fair', 'Literature showcase and book sales', 'Academic', 'Cairo International Book Fair Grounds, Nasr City', '2025-11-14', '10:00', 'Library Committee'),
('Coding Bootcamp', 'Intensive programming workshop', 'Technology', 'Greek Campus, Downtown Cairo', '2025-11-21', '09:00', 'IT Department'),
('Food Festival', 'International cuisine tasting event', 'Social', 'Nile Corniche, Garden City', '2025-11-28', '17:00', 'International Students Office'),
('Debate Championship', 'Inter-university debate competition', 'Academic', 'Faculty of Law, Cairo University, Giza', '2025-12-05', '14:00', 'Debate Society'),
('Winter Concert', 'Classical and modern music performances', 'Entertainment', 'Al-Azhar Mosque Complex, Islamic Cairo', '2025-12-12', '19:00', 'Music Department'),
('Gaming Tournament', 'Esports and board game competitions', 'Entertainment', 'City Center Mall, New Cairo', '2025-12-19', '12:00', 'Gaming Club'),
('New Year Celebration', 'Welcome 2026 campus party', 'Social', 'Nile Boat, Maadi Corniche', '2025-12-31', '21:00', 'Event Committee'),
('Research Symposium', 'Academic research presentations', 'Academic', 'National Research Center, Dokki', '2026-01-09', '09:00', 'Research Office'),
('Fashion Show', 'Student designer fashion showcase', 'Cultural', 'Four Seasons Hotel, Garden City', '2026-01-16', '18:00', 'Design Department'),
('Volunteer Fair', 'Community service opportunities showcase', 'Social', 'Abdeen Palace Museum, Downtown Cairo', '2026-01-23', '10:00', 'Community Service Office'),
('Language Exchange', 'Practice languages with international students', 'Academic', 'British Council, Agouza', '2026-01-30', '16:00', 'Language Center'),
('Film Festival', 'Student short films and documentaries', 'Entertainment', 'Zawya Cinema, Downtown Cairo', '2026-02-06', '18:00', 'Film Club'),
('Health & Wellness Fair', 'Health screenings and wellness workshops', 'Health', 'Medical City, Ain Shams', '2026-02-13', '09:00', 'Health Services'),
('Environmental Summit', 'Sustainability and climate change awareness', 'Academic', 'Botanical Garden, Giza', '2026-02-20', '10:00', 'Environmental Club'),
('Cultural Night', 'International students cultural presentations', 'Cultural', 'Citadel of Saladin, Old Cairo', '2026-02-27', '18:00', 'International Office'),
('Spring Sports Festival', 'Outdoor sports and activities', 'Sports', 'Al-Azhar Park, Islamic Cairo', '2026-03-06', '08:00', 'Athletic Department'),
('Technology Expo', 'Latest gadgets and tech innovations', 'Technology', 'Cairo ICT Conference Center, Smart Village', '2026-03-13', '10:00', 'Tech Society'),
('Graduation Ceremony Prep', 'Rehearsal and preparation for graduation', 'Academic', 'Cairo University Great Hall, Giza', '2026-03-20', '14:00', 'Academic Affairs'),
('Spring Break Kickoff', 'Pre-vacation celebration and activities', 'Social', 'Felucca Ride, Nile River, Maadi', '2026-03-27', '16:00', 'Student Activities');
